### ISSUE TITLE
Renderers can't access attributes values

### ISSUE THREAD

**Issue by ethauvin** [rife2/rife2#21]
Doing something like:

```java
var t = TemplateFactory.HTML.get("encodeUrl");
t.setBean(new ValueBean("a test &"));
t.getContent();
```

When the template is::

```
{{v render:rife.render.EncodeUrl:value/}}
```

No data will render.

Changing the template to:

```
{{v value/}}{{v render:rife.render.EncodeUrl:value/}}
```

Will output the value and rendered value, as expected.

The testable code is [here](https://github.com/rife2/rife2-template-renderers/blob/master/lib/src/test/java/rife/render/TestEncode.java#L28).

**Comment by ethauvin** [comment]
@gbevin Thanks, I'll try that.

**Comment by gbevin** [comment]
I think you're conflating a number of things, attributes are not values, they are simply objects associated with the template that are not rendered. Adding a value tag to a template without a default content will always end up rendering as the tag if you didn't set the value in code.

**Comment by ethauvin** [comment]
I was able to make it work using `template.getAttribute`, but if I include `{{v attributeName/}} anywhere in the template, `t.getContent()` still returns the raw template. By raw, I mean, the raw code, i.e.:

```
{{v value/}}{{v render:rife.render.EncodeUrl:value/}}
```

**Comment by gbevin** [comment]
@ethauvin can you give the exact code snippets you're using that exhibit this behavior?

**Comment by ethauvin** [comment]
@gbevin I just posted it to discord.
