### ISSUE TITLE
Templates with dash in their names are not found

### ISSUE THREAD

**Issue by ethauvin** [rife2/rife2#22]
Template name: `sample-test`

```java
 var t = TemplateFactory.TXT.get("sample-test");
```
Returns the following error:

```plain
Couldn't find template 'sample-test'.
```

Changed the template name to `sample2`

```java
 var t = TemplateFactory.TXT.get("sample2");
```

The template is now found.

I tried multiple combinations, as soon as dash is the name the template cannot be found.

**Comment by gbevin** [comment]
You'll get a stack trace that shows the actual name that was looked for, invalid Java identifier characters will be replaced by underscores. Sadly this is one of the limitations of compiling the templates to Java byte code and having a dedicated class for each template. The characters that can be used as the resulting class names can't support dashes and other characters.

**Comment by gbevin** [comment]
Added these details to the javadoc:
https://rife2.github.io/rife2/rife/template/TemplateFactory.html#get(java.lang.String,java.lang.String)
