### ISSUE TITLE
json response

### ISSUE THREAD

**Issue by sysmat** [rife2/rife2#25]
- I'm new to this lib, is it suitable for REST API?
- how to return JSON?

```java
get("/person", (Context c) -> {
            c.setContentType("application/json");
            c.print(new Person(1, "Tomaž", "Majerhold"));
        } );
```
- this dosen't work it use toString
- Dose this lib have middleware like logging, telemetry, ...?
- Dose routes have middleware like filter, validation, authentication?
- How you group routings?

**Comment by gbevin** [comment]
Hi, here are some answers to your questions:

## JSON:

* if you want to serialize an object to JSON, you can use an external library to do so, for instance JSON-java (org.json json). Here's an example of how to use that: https://www.baeldung.com/java-org-json.You can just print the JSONObject with the Context and it will be sent out.
* alternatively (and I use that the most), you can use the RIFE2 template engine to create a blueprint of the JSON response, and set the bean in the template, then print the template, for instance https://github.com/rife2/rife2/wiki/Template-Types#example-of-json-api-templating (thought this Java code sends the JSON to a service, you can use the template approach for returning it as a HTTP response)

## Logging, Telemetry:

This isn't integrated by default in the web engine.

## Filter, validation, authentication:

Yes, these are all supported and tightly integrated, for instance:
* filter: https://github.com/rife2/rife2/wiki/Site#element-chains
* validation: https://github.com/rife2/rife2/wiki/Validation
* authentication: https://github.com/rife2/rife2/wiki/Protected-Routes

## Group routings:

This wiki section shows how to group: https://github.com/rife2/rife2/wiki/Site#route-groups

**Comment by sysmat** [comment]
@gbevin thx for links

- I'm trying group but not working

```java
Router person = group("/person", new Router() {
        public void setup() {
            before(c -> {
                c.setContentType("application/json");
            } );
            get("", c ->  c.print(mapper.writeValueAsString(new Person(1, "Tomaž", "Majerhold"))));
            post("", c -> c.print("create person"));
            delete("", c -> c.print("delete person"));
            put("", c -> c.print("update person"));
//            after(c -> c.print(" after"));
        }
    });

    Router api = group("/api", person);
```

-  for GET `http://localhost:8080/api/person` I'm getting 404- Not Found

**Comment by gbevin** [comment]
Please use the discussions for help and further assistance:
https://github.com/orgs/rife2/discussions

What you basically did in your example is creating one router group that you set two routes up for, 
`/api` and `/person` both will get you to the the router you instantiated.

```java
    Router person_router = new Router() {
        public void setup() {
            before(c -> {
                c.setContentType("application/json");
            } );
            get("", c ->  c.print("root"));
            post("", c -> c.print("create person"));
            delete("", c -> c.print("delete person"));
            put("", c -> c.print("update person"));
        }
    };
    Router api = group("/api", new Router() {
        public void setup() {
            group("/person", person_router);
        }
    });
```

This does what you seem to want to do.

Alternatively you can do:

```java
    Router person_router = new Router() {
        public void setup() {
            before(c -> {
                c.setContentType("application/json");
            } );
            get("", c ->  c.print("root"));
            post("", c -> c.print("create person"));
            delete("", c -> c.print("delete person"));
            put("", c -> c.print("update person"));
        }
    };
    Router api = group("/api/person", person_router);
```

or also:

```java
    Router api = group("/api", new Router() {
        public void setup() {
            group("/person", new Router() {
                public void setup() {
                    before(c -> {
                        c.setContentType("application/json");
                    } );
                    get("", c ->  c.print("root"));
                    post("", c -> c.print("create person"));
                    delete("", c -> c.print("delete person"));
                    put("", c -> c.print("update person"));
                }
            });
        }
    });
```

**Comment by sysmat** [comment]
@gbevin thx for clarifying

- router API builder some thing like that   

```java
Router api = group("/api", new Router() {
        public void setup() {
            group("/person", person_router);
            group("/org", org_router);
    }});
```

**Comment by gbevin** [comment]
@sysmat yes that looks correct
