### ISSUE TITLE
Select prepared statement

### ISSUE THREAD

**Issue by sysmat** [rife2/rife2#27]
- is it possible to create prepared statement `select id, email where id = ?`
- I'm trying but I'm confused with api surface area

```java
CreateTable createQuery = new CreateTable(datasource)
        .table("aai_user")
        .column("id", Integer.class, 50)
        .column("mail", String.class, 255);

    Select selectQuery = new Select(datasource)
        .from(createQuery.getTable())
        .field("id")
        .field("mail")
// how to add where with parameter
// how to set value for parameter


```

**Comment by sysmat** [comment]
- or in MetaData, how to add table name, or column name for property?

**Comment by gbevin** [comment]
Hi @sysmat,

could you please ask for assistance in the discussions instead of opening issues:
https://github.com/orgs/rife2/discussions

If you open a topic in Q&A there, I'll follow up with some help.

Thank you!
