### ISSUE TITLE
Question/feature request: move bld to its own project

### ISSUE THREAD

**Issue by giorgiga** [rife2/rife2#35]
(sorry if this sounds blunt)

Are you working on (or have plans to/would not be opposed to PRs about) giving bld a life separate from that of the rife framework?

I'm asking because I was thinking of contributing (no promises - I haven't even looked at the source very well yet) and to me it makes a great deal of difference if bld is going to be a general-purpose build system that aims to take on gradle and maven, or if it will "just" (nothing bad about it, let's be clear) be the build component of the rife framework.

**Comment by gbevin** [comment]
Hi thanks for the question.

bld uses a lot of RIFE2 features and RIFE2 is only a 2.5MB jar file without any dependencies. We failed to see the point of trying to break it out. There's also many advantages to having RIFE2 features available for more advanced build logic, especially for CI purposes.

So in short, bld is an extension of the RIFE2 framework but is not intended to be used solely for RIFE2 framework builds.

**Comment by gbevin** [comment]
It might be worth pointing out that bld is designed to use extensions for anything besides its core features: https://github.com/rife2/rife2/wiki/Bld-Extensions

Writing new extensions is a great way to contribute and provide additional operations.

**Comment by giorgiga** [comment]
Thanks for the quick turnaround - I wish you all the best!

**Comment by gbevin** [comment]
Thank you!

**Comment by gbevin** [comment]
FYI, since there were other requests, we bit the bullet and bld is now available as its own project and repository:
https://github.com/rife2/bld
