### ISSUE TITLE
Split bld to its own project

### ISSUE THREAD

**Issue by hiljusti** [rife2/rife2#38]
I think bld is worth its own project. It's very close to the exact thing I've desired for years, and almost wrote but never got around to. I can only assume I'm not the only one. Opinions here are my own and I'm not speaking for the company, but where I'm coming from is that for a few years I've been a maintainer of Amazon and AWS's large-scale Java code base: especially the build systems. I think bld is exactly what the Java ecosystem at-large needs.

**Comment by gbevin** [comment]
Thanks for the feedback, here's what I'm struggling with regarding splitting up bld:

* bld relies on many parts of RIFE2, just not the web engine,
* I can also see parts for RIFE2 being very useful during builds, like the database engine, the abstracted resource finding, general purpose utils, ...
* there are no other dependencies it's just one 2.5MB jar and splitting things up in sub-projects is a genuine hassle without any practical gain except for maybe gaining 1MB
* I do get that there might be a perception thing, "why do I need a web framework with using a build tool, such bloat'? Are there other ways to some this?
* I don't want to make my own life more difficult by splitting things up in little pieces
* I don't want RIFE2 to have any dependencies, and I don't want bld to have any dependencies 

@hiljusti any thoughts or suggestions?

**Comment by hiljusti** [comment]
Hmm I yeah, I've only poked around a bit in the javadocs and codebase, but I can totally see that. I don't think it'd be possible to make a clean cut without complicating your life.

If it's possible, I'd like to pick your brain sometime on build systems

**Comment by gbevin** [comment]
Feel free to join us on Discord to chat

**Comment by gbevin** [comment]
This is underway https://github.com/rife2/bld
