### ISSUE TITLE
Scheduled task executes at non-scheduled times

### ISSUE THREAD

**Issue by ethauvin** [rife2/rife2#39]
I have the following for scheduled tasks:

```java
    private void setScheduler() {
        // DB Keep Alive
        var dbKeepAlive = new DbKeepAlive(datasource);
        scheduler.addExecutor(dbKeepAlive);
        scheduler.addTask(dbKeepAlive.createTask().frequencySpecification(EVERY_TWO_HOURS)
                .planned(Date.from(ZonedDateTime.now().plusHours(1).toInstant())));
        // Social Publisher
        socialPublisher = new SocialPublisher(this);
        scheduler.addExecutor(socialPublisher);

        // LastWatched Schedule
        final var lastWatched = new LastWatched(this);
        scheduler.addExecutor(lastWatched);
        scheduler.addTask(lastWatched.createTask().frequencySpecification(EVERY_TWO_HOURS));

        // TootsDuJour Schedule;
        final var hour = 2;
        final var now = ZonedDateTime.now();
        final ZonedDateTime firstTime;
        if (now.getHour() < hour) {
            firstTime = now.withHour(hour).withMinute(0).withSecond(0); // today 2 AM
        } else {
            firstTime = now.plusDays(1).withHour(hour).withMinute(0).withSecond(0); // tomorrow 2 AM
        }
        final var tootsDuJour = new TootsDuJour(this, firstTime);
        scheduler.addExecutor(tootsDuJour);
        scheduler.addTask(tootsDuJour.createTask().frequencySpecification("0 " + hour + " * * *")
                .planned(Date.from(firstTime.toInstant())));

        // Start scheduler
        scheduler.start();
    }
```

The `tootDuJour` task is set up to run at 2 am, yet at times it runs around midnight:

```
15-May-2023 00:00:30.001 INFO [343] net.thauvin.erik.blog.executors.DbKeepAlive.executeTask DbKeepAlive activated.
15-May-2023 00:00:34.420 INFO [net.thauvin.erik.blog.executors.TootsDuJour] net.thauvin.erik.blog.executors.TootsDuJour.post Toots du Jour (May 14) have been posted (9225)
```

It always happens when another task is running around midnight.

This is what it looks like when it is executed around 2 AM:

```
8-May-2023 02:00:30.001 INFO [net.thauvin.erik.blog.executors.DbKeepAlive] net.thauvin.erik.blog.executors.DbKeepAlive.executeTask DbKeepAlive activated.
18-May-2023 02:00:30.773 INFO [net.thauvin.erik.blog.executors.TootsDuJour] net.thauvin.erik.blog.executors.TootsDuJour.post Toots du Jour (May 17) have been posted (9233)
````

Am I doing something wrong, or is it a bug?

**Comment by gbevin** [comment]
The `.planned` specification is really only for once shot executions, it shouldn't be used together with repeating tasks. 

Also, using a specific pre-defined frequency is intended to be done through the `.frequency(Frequency)` method. The `.frequencySpecification(String)` method takes a full cron-like string specification. It wouldn't matter here, but you're doing needless conversions to string and then back to a frequency instance.

**Comment by ethauvin** [comment]
@gbevin To recap what we talked about:

-  If `.planned` is not used, all tasks will execute at startup and on the frequency.
-  I don't think that any of this explains why the `tootsDuJour` task is sometime executing at midnight, instead of 2 AM.

**Comment by ethauvin** [comment]
This is my configuration with the last snapshot:

```java
private void setScheduler() {
        // Social Publisher
        socialPublisher = new SocialPublisher(this);
        scheduler.addExecutor(socialPublisher);

        // LastWatched Schedule
        final var lastWatched = new LastWatched(this);
        scheduler.addExecutor(lastWatched);
        scheduler.addTask(lastWatched.createTask().frequencySpecification(EVERY_TWO_HOURS));

        // TootsDuJour Schedule;
        final var tootsDuJour = new TootsDuJour(this);
        scheduler.addExecutor(tootsDuJour);
        scheduler.addTask(tootsDuJour.createTask().frequencySpecification("0 2 * * *"));

        // Start scheduler
        scheduler.start();
    }
```

The `tootsDuJour` task executed at 00:00 today, not 02:00.

```
26-Aug-2023 00:00:32.843 INFO [net.thauvin.erik.blog.executors.TootsDuJour] net.thauvin.erik.blog.executors.TootsDuJour.post Toots du Jour (Aug 25) have been posted (9432)
```

**Comment by gbevin** [comment]
What does `EVERY_TWO_HOURS` look like?

**Comment by ethauvin** [comment]
> What does `EVERY_TWO_HOURS` look like?

```java
    private static final String EVERY_TWO_HOURS = "0 */2 * * *";
```

**Comment by gbevin** [comment]
Are you using a memory or a database scheduler?

**Comment by ethauvin** [comment]
> Are you using a memory or a database scheduler?

```java
    public final Scheduler scheduler = new MemoryScheduling().createScheduler();
```

**Comment by ethauvin** [comment]
@gbevin Triggered again at around midnight with today's snapshot.

**Comment by gbevin** [comment]
@ethauvin nothing strange happened in my isolated run, guess I'll switch to hours instead of minutes and try again

**Comment by ethauvin** [comment]
If you hover over the date, you can see the posting date/time:

https://erik.thauvin.net/blog/search?cat=mastodon

Seems to be 00:30 more often than not. It almost never fires at the scheduled time.

**Comment by gbevin** [comment]
Yeah I'm trying to reproduce it, but can't. This is a vary laborious process since I can't reproduce it at the minute scale either. So anything I try takes ages to verify. Next on my list is to try to write tests that could spoof the current time, but I'd have to adapt the scheduler code to be able to use that.

**Comment by ethauvin** [comment]
> Yeah I'm trying to reproduce it, but can't. This is a vary laborious process since I can't reproduce it at the minute scale either. So anything I try takes ages to verify. Next on my list is to try to write tests that could spoof the current time, but I'd have to adapt the scheduler code to be able to use that.

@gbevin Miight be a shot in the dark, but have you tried with Tomcat instead of Jetty?

**Comment by ethauvin** [comment]
> Yeah I'm trying to reproduce it, but can't. This is a vary laborious process since I can't reproduce it at the minute scale either. So anything I try takes ages to verify. Next on my list is to try to write tests that could spoof the current time, but I'd have to adapt the scheduler code to be able to use that.

If you give me some guidance on what you'd like to see output; I can put it on my server, and we'll have data by midnight.

**Comment by gbevin** [comment]
I'm trying to get it to happen locally so that I can debug it. At this point I have no clue where to start looking in the code.
