### ISSUE TITLE
Create cache / offline support e.g. with .m2

### ISSUE THREAD

**Issue by YunaBraska** [rife2/rife2#47]
I love this build system.
Would be nice to have the possibilities to use the `.m2` or `.gradle` or a new `.blb` global folder

**Comment by ethauvin** [comment]
Thanks @YunaBraska.

bld uses the `.m2` directory, just add `MAVEN_LOCAL` to your list of repositories.

You can also publish your artifacts to the `.m2` repository using:

```console
./bld compile publish-local
```

**Comment by YunaBraska** [comment]
Ah cool, must have missed it in the documentation

**Comment by YunaBraska** [comment]
ah, cool, that wasn't clear to me. thx.
